name: Build-All-Platforms

on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
    build:
      strategy:
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
  
      runs-on: ${{ matrix.os }}
  
      steps:
        - name: Check-out repository
          uses: actions/checkout@v4
  
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
  
        - name: Install Dependencies
          run: |
            pip install -r requirements.txt
  
        - name: Build Executable
          uses: Nuitka/Nuitka-Action@main
          with:
            nuitka-version: main
            script-name: screenshare.py
            standalone: true
            onefile: false
            include-package-data: |
              flask_bootstrap
            include-data-dir: |
              static=static
              templates=templates
  
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{ runner.os }} Build
            path: |
              build/*.exe
              build/*.bin
              build/*.app/**/*
              build/static/**
              build/templates/**
            include-hidden-files: true